; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.1.3 on Sat Jun 13 2020 15:20:33 GMT-0500 (Central Daylight Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


