; pause.g
; called when a print from SD card is paused
;
; generated by RepRapFirmware Configuration Tool v3.1.3 on Sat Jun 13 2020 15:20:35 GMT-0500 (Central Daylight Time)
M83            ; relative extruder moves
G1 E-2 F3600   ; retract 2mm of filament
G91            ; relative positioning
G1 Z5 F5000    ; lift Z by 5mm
G90            ; absolute positioning
G1 X0 Y0 F6000 ; go to X=0 Y=0

